// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxkxkydeluflivpfnyhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14a3hreWRlbHVmbGl2cGZueWhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTYxMzcsImV4cCI6MjA2NjUzMjEzN30.0PmQrUlrtVMFjqbcr-SUHPJi-y9neLsVXGjwP2kZWW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);